# Generated by Django 3.1 on 2020-08-26 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_practical', '0002_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Sale Summary',
                'verbose_name_plural': 'Sales Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_practical.topic',),
        ),
    ]
