# Generated by Django 3.1 on 2020-08-26 09:15

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('django_practical', '0003_salesummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleSummary',
        ),
        migrations.CreateModel(
            name='UserOverride',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
